openapi: 3.0.0
info:
  title: newsfeedapi-new
  version: '1.0'
  contact:
    name: Crypto Investor Stream Api Team
    url: 'http://cryptonvestor.stream/api'
    email: api@cryptoinvestor.stream
  description: ''
  termsOfService: 'https://cryptoinvestor.stream/terms'
  license:
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    name: Apache 2.0
servers:
  - url: 'http://api.cryptoinvestor.stream/v1'
paths:
  /currencies:
    get:
      summary: /currencies
      tags:
        - Currencies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: currency id
                    example: '23'
                  name:
                    type: string
                    description: currency name
                    example: Bitcoin
                  symbol:
                    type: string
                    description: currency symbol
                    example: BTC
                  active:
                    type: boolean
                    description: The status of the currency
                  rank:
                    type: string
                    description: the rank of the currency based on volume
                    example: '1'
              examples:
                example:
                  value:
                    - id: 1
                      name: Bitcoin
                      symbol: BTC
                      active: '1'
                      rank: '1'
                    - id: 3
                      name: Ethereum
                      symbol: ETH
                      active: '1'
                      rank: '2'
      operationId: get-currencies
      description: "Returns a list of all supported currencies. Always use the id's gathered here to lookup data for specific currencies. "
      parameters:
        - schema:
            type: string
          in: query
          name: verticals
          description: 'Optional: Limit the results to currencies in the provided verticals'
        - schema:
            type: string
            default: active
            enum:
              - active
              - inactive
              - all
          in: query
          name: listing_status
          description: 'Optional: By default only active projects are listed. To list non active currencies set the listing_status=all'
        - schema:
            type: string
            enum:
              - id
              - rank
            default: id
          in: query
          name: sort
          description: 'Optional: the value to sort the results on, valid option are: id and rank'
        - schema:
            type: string
            default: '1'
          in: query
          name: start
          description: Optionally offset the start (1-based index) of the paginated list of items to return.
        - schema:
            type: string
            default: '100'
          in: query
          name: limit
          description: 'Optional: The amount of results to return'
  /currencies/metadata:
    get:
      summary: /currencies/metadata
      tags:
        - Currencies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of the currency
                    example: '1'
                  name:
                    type: string
                    description: Name
                    example: Bitcoin
                  bio_short:
                    type: string
                    description: Short description
                    example: Bitcoin (BTC) is a consensus network that enables a new payment system and a completely digital currency.
                  bio_long:
                    type: string
                    description: Long description of the currency
                    example: 'Bitcoin (BTC) is a consensus network that enables a new payment system and a completely digital currency. Powered by its users, it is a peer to peer payment network that requires no central authority to operate. On October 31st, 2008, an individual or group of individuals operating under the pseudonym "Satoshi Nakamoto" published the Bitcoin Whitepaper and described it as: "a purely peer-to-peer version of electronic cash, which would allow online payments to be sent directly from one party to another without going through a financial institution."'
                  logo_url:
                    type: string
                    description: Link to the logo
                    format: uri
                    example: 'https://s3.us-east-2.amazonaws.com/cryptoinvestorstream/static/images/currencies/btc.svg'
                  hq_location:
                    type: string
                    description: Headquaters location
                    example: New York
                  vertical:
                    type: array
                    description: The verticals the currency belongs to
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the vertical
                          example: '1'
                        name:
                          type: string
                          description: name of the vertial
                          example: Healthcare
                        description:
                          type: string
                          description: Description of the vertical
                          example: Currencies in the healthcare business
                  links:
                    type: array
                    description: Links related to the currency
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          description: Link type
                          example: website
                        url:
                          type: string
                          description: URL to the link
                          example: 'https://www.bitcoin.com'
                  communities:
                    type: array
                    description: Communities for the currency
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          description: Community type
                          example: twitter
                        url:
                          type: string
                          description: URL to the community
                          example: 'http://www.twitter.com/@bitcoin'
                  symbol:
                    type: string
                    description: The symbol of the currency
                    example: BTC
                  rankl:
                    type: string
                    description: 'The rank of the currency '
                    example: '1'
                  platform_symbol:
                    type: string
                  platform_token_address:
                    type: string
              examples:
                example:
                  value:
                    id: '1'
                    symbol: BTC
                    logo_url: 'https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/btc.svg'
                    bio_short: Bitcoin is a cryptocurrency.
                    bio_long: Bitcoin is a cryptocurrency. It is a decentralized digital currency
                    bio_keywords: 'BTC,Bitcoin'
                    hq_location: Malta
                    vertical_types:
                      id: '12'
                      name: Healthcare
                      description: Currencies that are in the healthcare business
                    communities:
                      - type: twitter
                        url: 'http://www.twitter.com/bitcoin'
                      - type: discord
                        url: 'http://www.discord.com/bitcoin'
                    links:
                      - type: website
                        url: 'http://www.bitcoin.com'
                      - type: website
                        url: 'http://www.bitcoin.com'
      operationId: get-currencies-metadata
      description: Get detailed meta information about the currency
      parameters:
        - schema:
            type: string
          in: query
          name: ids
          description: The id or ids of the currencies you want the metadata for
          required: true
        - schema:
            type: string
            default: 'name,bio_short,bio_long,logo_url,hq_location,vertical,links,communities,symbol,rank'
          in: query
          name: aux
          description: Optionally specify a comma-separated list of data fields to return.
    parameters: []
  /currencies/ticker:
    get:
      summary: /currencies/ticker
      tags:
        - Currencies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of the currency
                    example: '1'
                  symbol:
                    type: string
                    description: symbol of the currency
                    example: BTC
                  price:
                    type: string
                    description: 'price default in USD, use convert to change to a different currency'
                    example: '8451.36516421'
                  price_date:
                    type: string
                    description: last update of the price in RFC3339
                    example: '2018-07-05T15:00:00Z'
                  circulating_supply:
                    type: string
                    description: circulating supply of the currency
                    example: '17758462'
                  max_supply:
                    type: string
                    description: maximum supply of the currency
                    example: '21000000'
                  logo_url:
                    type: string
                    description: URL for the logo of the currency
                    format: uri
                    example: 'https://s3.us-east-2.amazonaws.com/cis/static/images/currencies/btc.svg'
                  market_cap:
                    type: string
                    description: 'currenct marketcap of the currency in USD, use convert to change to a different currency'
                    example: '150083247116.70'
                  rank:
                    type: string
                    description: rank of the currency based on volume
                    example: '1'
                  ath:
                    type: string
                    description: 'All time high of the currency in USD, use convert to change to a different currency'
                    example: '19404.81116899'
                  ath_date:
                    type: string
                    description: The date on which the ATH was reached
                    format: date
                    example: '2017-12-16'
                  timeframe:
                    type: object
                    description: 'Timeframe for the data eg. 1h, 24h, 7d, 30d'
                    properties:
                      price_change:
                        type: string
                        description: 'Change in price in USD, use convert to change to a different currency'
                        example: '269.75208019'
                      price_change_pct:
                        type: string
                        description: Percent change of price for the given timeframe
                        example: '0.03297053'
                      volume:
                        type: string
                        description: 'Total volume for the given timeframe, default in USD'
                        example: '1110989572.04'
                      volume_change_pct:
                        type: string
                        description: Percent change of volume for the given timeframe
                        example: '24130098.49'
                      market_cap_change:
                        type: string
                        description: Amount of market cap change for the given timeframe
                        example: '4805518049.63'
                      market_cap_change_pct:
                        type: string
                        description: Percent change of market_cap for the given timeframe
                        example: '0.03'
                  quote-currency:
                    type: string
                    description: Quote currency
                    example: USD
              examples:
                example:
                  value:
                    id: '1'
                    price: '8451.36516421'
                    price_date: '2019-06-14'
                    symbol: BTC
                    circulating_supply: '17758462'
                    max_supply: '21000000'
                    name: Bitcoin
                    logo_url: 'https://s3.us-east-2.amazonaws.com/cis/static/images/currencies/btc.svg'
                    market_cap: '150083247116.70'
                    rank: '1'
                    high: '19404.81116899'
                    high_timestamp: '2017-12-16'
                    quote_cuurency: EUR
                    1d:
                      price_change: '269.75208019'
                      price_change_pct: '0.03297053'
                      volume: '1110989572.04'
                      volume_change: '-24130098.49'
                      volume_change_pct: '-0.02'
                      market_cap_change: '4805518049.63'
                      market_cap_change_pct: '0.03'
      operationId: get-currencies-ticker
      parameters:
        - schema:
            type: string
          in: query
          name: ids
        - schema:
            type: string
          in: query
          name: convert
        - schema:
            type: string
            default: 'id,symbol,price,price_date,circulating_supply,max_supply,logo_url,market_cap,rank,ath,ath_date,timeframe=1h,quote_currency=USD'
          in: query
          name: aux
          description: Optionally specify a comma-separated list of data fields to return.
        - schema:
            type: string
            default: 1h
          in: query
          name: timeframe
          description: 'Enter a comma seperated list of time frames. Valid values are: 5m, 15m, 30m, 1h, 2h, 4h, 1d, 7d, 30d'
      description: 'Price, volume, market cap, and rank for all currencies across 5 minute, 15 minute, 30minute, 1 hour, 1 day, 7 day, 30 day, 365 day, and year to date intervals. Current prices are updated every minute'
  /exchanges:
    get:
      summary: exchanges
      responses:
        '200':
          description: A list of supported exchanges and the metadata information
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the exchange
                  country:
                    type: string
                    description: 'Country where the exchnge is based out of '
                  active:
                    type: boolean
                    description: Is the exchange operational
                  region:
                    type: string
                    description: Region where the exchange operates
                  last_update:
                    type: string
                    description: When was this information last updated
                  blog:
                    type: string
                    description: URL for the blog of the exchange
                  website:
                    type: string
                    description: Website URL for the exchange
                  twitter:
                    type: string
                    description: Twitter URL for the exchange
                  telegram:
                    type: string
                    description: Link to the Telegram community for the exchange
                  fees:
                    type: string
                    description: Link to fees page
                  rank:
                    type: string
                    description: Rank of the exchange based on adjusted volume
                  id:
                    type: string
                  grades:
                    type: object
                    properties:
                      legal:
                        type: string
                      investment:
                        type: string
                      team:
                        type: string
                      data_provision:
                        type: string
                      trade_monitoring:
                        type: string
                      market_quality:
                        type: string
                      security:
                        type: string
                      negative_reports_penalty:
                        type: string
                      grade:
                        type: string
                      grade_points:
                        type: string

                  volume:
                    type: object
                    properties:
                      volume_24h:
                        type: string
                      volume_7d:
                        type: string
                      volume_30d:
                        type: string
                      volume_24h_change_percent:
                        type: string
                      volume_7d_change_percent:
                        type: string
                      volume_30d_change_percent:
                        type: string
              examples:
                example:
                  value:
                    - id: '2'
                      name: Binance
                      description: 'Binance is a global cryptocurrency exchange that provides a platform for trading more than 100 cryptocurrencies. Since early 2018, Binance is considered as the biggest cryptocurrency exchange in the world in terms of trading volume'
                      region: eu
                      country: Malta
                      blog: 'http://binance.com/blog'
                      twitter: 'http://twitter.com/binance'
                      telegram: 'https://t.me/binanceexchange'
                      fees: 'https://www.binance.com/en/fee/schedule'
                      website: 'https://www.binance.com'
                      volume_24h: '236797947.38'
                      volume_7d: '4334436797947.38'
                      volume_30d: '34343433797947.38'
                      volume_24h_change_pct: '1.5563'
                      volume_7d_change_pct: '2.3343'
                      volume_30d_change_pct: '3.2333'
                      rating:
                        grade: A
                        grade_points: '41,1'
                        grade_points_sections:
                          legal: '5,9'
                          investment: '1,3'
                          team: '5,2'
                          data_provision: '10,7'
                          trade_monitoring: '0,0'
                          market_quality: '11,0'
                          security: '7,4'
                          negative_reports_penalty: '0,0'
            application/xml:
              schema:
                type: object
                properties: {}
      operationId: get-exchanges
      description: Get a list of supported exchanges
      parameters:
        - schema:
            type: string
            default: id
          in: query
          name: sort
          description: 'Optional: the value to sort the results on, valid option are: id, rank, name'
        - schema:
            type: string
          in: query
          name: start
          description: Optionally offset the start (1-based index) of the paginated list of items to return.
        - schema:
            type: string
            default: '25'
          in: query
          name: limit
          description: 'Optional: The amount of results to return'
        - schema:
            type: string
            default: 'id,name,country,active,region,last_update,blog,website,twitter,telegram,fees,rank,volume'
          in: query
          name: aux
          description: Optionally specify a comma-separated list of supplemental data fields to return.
      tags:
        - Exchanges
  /market:
    get:
      summary: /market
      tags:
        - Market
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  quote:
                    type: object
                    properties:
                      quote_currency:
                        type: object
                        description: Market information in converted currency default is USD
                        properties:
                          total_marketcap:
                            type: string
                            description: 'Total marketcap '
                          total_volume_24h:
                            type: string
                            description: Total volume in the last 24 hours
                          altcoin_volume_24h:
                            type: string
                            description: Altcoin volume in the last 24 hours
                          altcoin_marketcap:
                            type: string
                            description: Total altcoin marketcap
                          last_update:
                            type: string
                            description: Time of the last update
                  eth-dominance:
                    type: string
                    description: "Ethereum's market dominance percentage by market cap."
                  fear-and-greed:
                    type: object
                    description: Fear and greed index values
                    properties:
                      value:
                        type: string
                        description: 'Value of the fear and greed index '
                      value_specification:
                        type: string
                        description: 'Value specification Extreme Fear, Fear, Greed, Extreme Greed'
                      last_update:
                        type: string
                        description: Time of the last update of the fear and greed value
                      24h_change_percent:
                        type: string
                        description: Percentage change in the last 24 hours in the fear and greed index
                  eth_dominance_24h_change_percent:
                    type: string
                    description: 24h change percentage in the ETH dominance
                  btc_dominance_24h_change_percent:
                    type: string
                    description: 24h change percentage in the BTC dominance
                  btc-dominace:
                    type: string
                    description: "Bitcoin's market dominance percentage by market cap."
              examples:
                example:
                  value:
                    btc_dominace: '69.23'
                    btc_dominance_24h_change_percent: '1.75'
                    eth_dominance: '10.23'
                    eth_dominance_24h_change_percent: '-2.25'
                    fear-and-greed-index:
                      value: '987'
                      value_classification: A
                      timestamp: '2019-12-16T18:47:00.000Z'
                      24h_change_percent: '2.3'
                    last_update: '2019-05-16T18:47:00.000Z'
                    quote:
                      USD:
                        total_market_cap: 250385096532.124
                        total_volume_24h: 119270642406.968
                        altcoin_volume_24h: 119270642406.968
                        altcoin_market_cap: 250385096532.124
                        last_updated: '2019-05-16T18:47:00.000Z'
      operationId: get-market
      description: 'Returns the latest global cryptocurrency market metrics. Use the "convert" query paramter  to return market values in multiple fiat and cryptocurrency conversions in the same call.'
      parameters:
        - schema:
            type: string
          in: query
          name: convert
          description: he currency to convert the default USD values to. Must be a Fiat currency. Use the /conversion-rates endpoint to check which currencies are available
  /news:
    get:
      summary: /news
      tags:
        - News
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  source:
                    type: object
                    description: Information about the source of the news article
                    properties:
                      name:
                        type: string
                        description: Name of the news source
                      url:
                        type: string
                        description: URL of the news source
                        format: uri
                  currencies:
                    type: array
                    description: A list of currencies the news article relates to
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the currency. Get a list of all currency ids via /currencies/
                        name:
                          type: string
                          description: Name of the currency
                        symbol:
                          type: string
                          description: Symbol of the currency
                  categories:
                    type: array
                    description: List of categories the news article related to. Get all categories with /news/categories
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the category
                        keywords:
                          type: string
                          description: keywords which describe the category
                  tags:
                    type: array
                    description: Tags related to the news article
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: 'id of the tag, get all tags with /news/tags'
                        name:
                          type: string
                          description: Name of the tag
                  link:
                    type: string
                    description: Link to the news article
                    format: uri
                  title:
                    type: string
                    description: Title of the news article
                  excerpt:
                    type: string
                    description: Excerpt of the news article
                  full-article:
                    type: string
                    description: Full article text
                  publish_date:
                    type: string
                    format: date-time
                    description: Publish date of the article
                  sentiment:
                    type: string
                    description: Sentiment of the article
                  expert-level:
                    type: string
                    description: Expert level of the audience this article is suitable for
                  region:
                    type: string
                    description: Region or language this artivle is suitable for
              examples:
                example:
                  value:
                    id: '2332'
                    source:
                      id: ''
                      name: ''
                      url: ''
                    currencies:
                      - id: '2'
                        symbol: ETH
                        name: Ethereum
                      - id: '1'
                        symbol: BTC
                        name: Bitcoin
                    categories:
                      - id: '1'
                        name: Project news
                      - id: '2'
                        name: Regulation
                    tags:
                      - id: '1'
                        name: stablecoins
                    link: 'https://www.newsbtc.com/2020/02/13/okex-btcusd-options-registers-trading-volume-of-usd175-6m-volume-in-its-very-first-month/'
                    title: OKEx BTCUSD Options Registers Trading Volume of USD175.6M Volume in its Very First Month
                    excerpt: The leading cryptocurrency and digital asset trading platform OKEx is having a great run as it continues to provide world-class trading products for the global crypto community. The recently launched BTCUSD options trading feature on the platform is reported to have garnered volumes of around $176 million within a span of one month. The figures...
                    publish_date: '2018-07-05T15:00:00Z'
                    sentiment: POSITIVE
                    expert_level: PRO
                    region: en
      operationId: get-news
      parameters:
        - schema:
            type: string
            enum:
              - en
              - fr
              - es
              - pt
              - de
              - nl
            default: en
          in: query
          name: region
          description: 'Select the region/language to limit the results to. '
        - schema:
            type: string
          in: query
          name: ids
          description: List of currency ids to limit the results to
        - schema:
            type: string
            default: '10'
            maxLength: 0
            minLength: 1
          in: query
          name: limit
          description: Amount of news articles to limit the results to
        - schema:
            type: string
          in: query
          name: verticals
          description: List of vertical ids to limit the results to
        - schema:
            type: string
            maxLength: 0
            minLength: 1
          in: query
          name: start
          description: Optionally offset the start (1-based index) of the paginated list of items to return.
      description: 'Returns a curated lists of the latest news items. '
    parameters: []
  /news/sources:
    get:
      summary: /news/sources
      tags:
        - News
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of the source
                    example: '1'
                  name:
                    type: string
                    description: Name of the source
                    example: NewsBTC
                  url:
                    type: string
                    description: URL of the source website
                    example: 'https://newsbtc.com'
                  region:
                    type: string
                    example: en
                    description: The region/language a source is in
              examples:
                example:
                  value:
                    - id: '2'
                      name: NewsBTC
                      url: 'https://www.newsbtc.com/'
                    - id: '4'
                      name: Trustnodes
                      url: 'https://www.trustnodes.com/'
      operationId: get-news-sources
      description: Returns a list of the sources used in the news feed
      parameters:
        - schema:
            type: string
            default: en
          in: query
          name: region
          description: 'Optional: Limit results to sources from the specified regions'
  /news/categories:
    get:
      summary: /news/categories
      tags:
        - News
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of the category
                    example: '1'
                  name:
                    type: string
                    description: name of the category
                    example: adoptation
              examples:
                example:
                  value:
                    - id: '1'
                      name: adoptation
                    - id: '2'
                      name: analysis
                    - id: '3'
                      name: exchange listing
      operationId: get-news-categories
      description: Returns a list of available categories
  /news/tags:
    get:
      summary: /news/tags
      tags:
        - News
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of the tag
                  name:
                    type: string
                    description: name of the tag
              examples:
                example:
                  value:
                    - id: '1'
                      name: stablecoins
                    - id: '2'
                      name: security
                    - id: '3'
                      name: malware
      operationId: get-news-tags
      description: Returns a list of tags which are used
  /news/twitter:
    get:
      summary: /news/twitter
      tags:
        - News
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  source:
                    type: object
                    description: Source of the tweet
                    properties:
                      id:
                        type: string
                        description: id of the source
                        example: '2'
                      username:
                        type: string
                        description: username of the source
                        example: '@binance'
                      bio:
                        type: string
                        description: bio of the source
                        example: The number one exchange
                      region:
                        type: string
                        description: region for the source
                        enum:
                          - en
                          - de
                          - es
                          - pt
                          - nl
                        example: en
                      name:
                        type: string
                        description: name of the source
                        example: Binance
                  categories:
                    type: array
                    description: Array of categories the tweet content relates to
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the category
                          example: '4'
                        name:
                          type: string
                          description: name of the category
                          example: analysis
                  currencies:
                    type: array
                    description: Currencies which are mentianed in the tweet
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the currency
                          example: '1'
                        name:
                          type: string
                          description: name of the currency
                          example: Bitcoin
                        symbol:
                          type: string
                          description: symbol of the currency
                          example: BTC
                  tags:
                    type: array
                    description: aray of tags which are related to the tweet content
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the tag
                        name:
                          type: string
                          description: name of the tag
                  message:
                    type: string
                    description: message content of the twitter message
                  message_id:
                    type: string
                    description: message_id of the twitter message
                  publish_date:
                    type: string
                    format: date-time
                    description: publish date of the twitter message in RFC3999
                  sentiment:
                    type: string
                    description: sentiment of the twitter message
                    enum:
                      - POSITIVE
                      - NEUTRAL
                      - NEGATIVE
                  retweet_count:
                    type: string
                    description: number of retweets for the tweet
                  favorite_count:
                    type: string
                    description: favorite count for the tweet
                  expert_level:
                    type: string
                    description: the expert level of the audience this tweet is suitable for.
                    enum:
                      - PRO
                      - INTERMEDIATE
                      - BEGINNER
                  exchanges:
                    type: array
                    description: exchanges mentioned in the tweet
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the exchange
                        name:
                          type: string
                          description: name of the exchange
              examples:
                example:
                  value:
                    id: ''
                    source:
                      id: '2'
                      name: Binance
                      username: '@binance'
                      bio: The number one exchange
                      region: en
                    currencies:
                      - id: '2'
                        symbol: ETH
                        name: Ethereum
                      - id: '1'
                        symbol: BTC
                        name: Bitcoin
                    categories:
                      - id: '1'
                        name: Project news
                      - id: '2'
                        name: Regulation
                    exchanges:
                      - id: '1'
                        name: Binance
                    tags:
                      - id: '1'
                        name: stablecoins
                    message: 'At #Crypto Center we are looking for franchisees with an entrepreneurial &amp; managerial spirit, a strong sense of interpersonal skills. #Franchisees who know how to train &amp; motivate their employees, driven by passion.In-depth :play_button: https://t.co/4H6I2jh1tx#Peculium #invest #success https://t.co/4ykvMnydEj'
                    message_id: '12123123344555'
                    publish_date: '2018-07-05T15:00:00Z'
                    sentiment: POSITIVE
                    retweet_count: '121'
                    favorite_count: '2323'
                    expert_level: PRO
                    link: 'https://www.newsbtc.com/2020/02/13/okex-btcusd-options-registers-trading-volume-of-usd175-6m-volume-in-its-very-first-month/'
                    title: OKEx BTCUSD Options Registers Trading Volume of USD175.6M Volume in its Very First Month
                    excerpt: The leading cryptocurrency and digital asset trading platform OKEx is having a great run as it continues to provide world-class trading products for the global crypto community. The recently launched BTCUSD options trading feature on the platform is reported to have garnered volumes of around $176 million within a span of one month. The figures...
      operationId: get-news-twitter
      description: Return the latest twitter messages
      parameters:
        - schema:
            type: string
          in: query
          name: ids
          description: 'Optional: List of currency ids to limit results to.'
        - schema:
            type: string
          in: query
          name: verticals
          description: 'Optional: Limit the results to tweet from currencies in the specified verticals.'
        - schema:
            type: string
          in: query
          name: start
          description: Optionally offset the start (1-based index) of the paginated list of items to return.
        - schema:
            type: string
            default: '10'
          in: query
          name: limit
          description: 'Optional: Amount of news articles to limit the results to'
  /news/twitter-sources:
    get:
      summary: /news/twitter-sources
      tags:
        - News
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: '1'
                    description: id of the twitter source
                  name:
                    type: string
                    example: Binance
                    description: name of the twitter source
                  username:
                    type: string
                    example: '@binance'
                    description: username for the twitter source
                  bio:
                    type: string
                    example: The number one exchange by volume
                    description: bio of the twitter source
                  region:
                    type: string
                    description: region for the source
                    enum:
                      - en
                      - de
                      - fr
                      - es
                      - pt
                      - nl
                    example: en
                  active:
                    type: boolean
                    description: status of the source
                  type:
                    type: string
                    description: 'The type of source. '
                    enum:
                      - currency
                      - exchange
                      - influencer
                  twitter_id:
                    type: string
                    description: twitter id needed to generate urls
              examples:
                example:
                  value:
                    - id: '1'
                      name: Binance
                      username: '@binance'
                      bio: The number one exchange
                      region: en
                      active: true
                    - id: '2'
                      name: Coinbase
                      username: '@coinbase'
                      bio: One of the most used entry level exchange
                      region: en
                      active: true
      operationId: get-news-twitter-sources
      description: Return a list of sources used to receive tweets
      parameters:
        - schema:
            type: string
          in: query
          name: region
          description: 'Optional: Limit results to twitter sources in the specified regions'
        - schema:
            type: string
            default: all
          in: query
          name: source_type
          description: A comme seperated list of the source_types to return
  /events:
    get:
      summary: /events
      tags:
        - Events
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Event id
                  title:
                    type: string
                    description: Title of this event
                  currencies:
                    type: array
                    description: List of currencies associated with this event
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the currency
                        symbol:
                          type: string
                          description: symbol of the currency
                  date_event:
                    type: string
                    description: Date of this event
                  can_ocur_before:
                    type: boolean
                    description: Indicates whether this event can occur before its date
                  categories:
                    type: array
                    description: Array of categorie Object associated with this event
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the category
                        name:
                          type: string
                          description: Name of the category
                  proof:
                    type: string
                    description: Screenshot proof for this event
                  description:
                    type: string
                  percentage:
                    type: string
                    description: Indicates whether an event is legitimate or not (algorithm based on votes and status)
                  vote_count:
                    type: string
                    description: Total number of votes for this event
                  positive_vote_count:
                    type: string
                    description: Number of positive votes for this event
                  is_hot:
                    type: boolean
                    description: Indicates whether an event is hot or not
                  is_trending:
                    type: boolean
                    description: Indicates whether an event is trending or not
                  is_significant:
                    type: boolean
                    description: Indicates whether an event is significant or not
                  is_controversial:
                    type: boolean
                    description: Indicates whether an event is controversial or not
                  hot_index:
                    type: string
                    description: Underlying data to determine whether an event is hot or not (algorithm based on votes and views)
                  trending_index:
                    type: string
                    description: Underlying data to determine whether an event is trending or not (algorithm based on votes and views)
                  significant_index:
                    type: string
                    description: 'Underlying data to determine whether an event is significant or not (algorithm based on votes, views and market cap)'
                  controversial_index:
                    type: string
                    description: Underlying data to determine whether an event is controversial or not (algorithm based on votes and views)
                  confirmed_by_officials:
                    type: boolean
                    description: Indicates whether an event has been confirmed by official representatives or not
                  original_source:
                    type: string
                    description: Link to the original source of the event
              examples:
                example:
                  value:
                    - id: '223'
                      title: Blockchain Economy 2020
                      currencies:
                        - id: '1'
                          symbol: BTC
                        - id: '2'
                          symbol: ETH
                      date_event: '2020-02-20'
                      can_ocur_before: false
                      categories:
                        - id: '2'
                          name: Conference
                        - id: '4'
                          name: Community
                      proof: 'https://d32bfp67k1q0s7.cloudfront.net/25864f9dd39985585787be305ec4f873.png'
                      description: ''
                      percentage: '96.92'
                      vote_count: '1000'
                      positive_vote_count: '998'
                      is_hot: 'true'
                      is_trending: 'false'
                      is_significant: 'true'
                      is_controversial: 'true'
                      hot_index: '198977'
                      trending_index: '12'
                      significant_index: '345'
                      controversial_index: '10'
                      confirmed_by_officials: 'true'
                      original_source: 'https://awesomeurl.com'
      operationId: get-events
      description: List of upcoming and previous events
      parameters:
        - schema:
            type: string
          in: query
          name: date
          description: 'Optional: data to show events for'
        - schema:
            type: string
          in: query
          name: ids
          description: 'Optional: List of currency ids to show events for'
  /events/categories:
    get:
      summary: /events/categories
      tags:
        - Events
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of the event category
                  name:
                    type: string
                    description: name of the event category
              examples:
                example:
                  value:
                    - id: '1'
                      name: Release
                    - id: '2'
                      name: Burn
      operationId: get-events-categories
      description: Returns a list of event categories
  /currency/verticals:
    get:
      summary: /currency/verticals
      tags:
        - Currencies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of the vertical
                  name:
                    type: string
                    description: name of the vertical
                  description:
                    type: string
                    description: description of the vertical
              examples:
                example:
                  value:
                    - id: '2'
                      name: Healthcare
                    - id: '3'
                      name: DeFi
      operationId: get-currency-verticals
      description: 'Returns a list of verticals a currency can belong to. '
  /currencies/exchange-rates:
    get:
      summary: /currencies/exchange-rates
      tags:
        - Currencies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  currency:
                    type: string
                    description: Currency ISO code
                  rate:
                    type: string
                    description: Rate at which to convert from USD
                  last_update:
                    type: string
                    description: last time the rate was updated
              examples:
                example:
                  value:
                    - currency: AED
                      rate: 0.27224
                      last_update: '2020-02-21T19:47:24.554601+01:00'
                    - currency: AFN
                      rate: 0.01296
                      last_update: '2020-02-21T19:47:24.557480+01:00'
                    - currency: ALL
                      rate: 0.00883
                      last_update: '2020-02-21T19:47:24.560105+01:00'
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  currency:
                    type: string
                  rate:
                    type: string
      operationId: get-currencies-exchange-rate
      description: A list of the available exchange rates used to convert currency prices
      parameters:
        - schema:
            type: string
          in: query
          name: currencies
          description: List of currencies to return the exchange rate for
    parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key Query:
      name: api_key
      type: apiKey
      in: query
    API Key Header:
      name: X-API-KEY
      type: apiKey
      in: query
tags:
  - name: Currencies
    description: Endpoints related to getting currency price and metadata
  - name: Exchanges
    description: Endpoints which provide information about exchanges
  - name: Events
    description: Endpoints related to event information. Get the latest events related to crypto currencies
  - name: Market
    description: 'General market information like global marketcap, fear and greed index.'
  - name: News
    description: Endpoints that return the latest curated news and social information about the market
