{
  "openapi": "3.0.0",
  "info": {
    "title": "Crypto Investor API",
    "description": "API for fetching cryptocurrency price, market and news information.",
    "contact": {
      "email": "api@cryptoinvestor.stram"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.cryptoinvestor.stream/v1",
      "description": "CryptoInverstor.stream API"
    }
  ],
  "tags": [
    {
      "name": "private",
      "description": "Secured Admin-only calls"
    },
    {
      "name": "partners",
      "description": "Operations available to registered partners"
    },
    {
      "name": "public",
      "description": "Public accessable calls."
    }
  ],
  "paths": {
    "/news": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/newsItem"
                },
                "examples": {
                  "example-1": {}
                }
              }
            }
          }
        },
        "operationId": "get-news",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "region",
            "description": "region or commaseperated list of regions to limit the results to"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "ids",
            "description": "list of currencies to limit results for"
          },
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "limit",
            "description": "number of news items to return"
          }
        ]
      }
    },
    "/currencies": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "name": {
                      "type": "string"
                    },
                    "symbol": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "example": {
                    "value": [
                      {
                        "id": 1,
                        "name": "Bitcoin",
                        "symbol": "BTC"
                      },
                      {
                        "id": 3,
                        "name": "Ethereum",
                        "symbol": "ETH"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-price",
        "description": "Returns a list of all supported currencies. Always use the id's gathered here to lookup data for specific currencies. "
      },
      "parameters": []
    },
    "/news/sources": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {},
        "operationId": "get-news-sources"
      }
    },
    "/currencies/metadata": {
      "parameters": [],
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/currency-metadata"
                },
                "examples": {
                  "example": {}
                }
              }
            }
          },
          "": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/currency-metadata"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "1",
                      "symbol": "BTC",
                      "logo_url": "https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/btc.svg",
                      "bio_short": "Bitcoin is a cryptocurrency.",
                      "bio_long": "Bitcoin is a cryptocurrency. It is a decentralized digital currency",
                      "bio_keywords": "BTC,Bitcoin",
                      "hq_location": "Malta",
                      "vertical_types": {
                        "id": "269.75208019",
                        "name": "0.03297053",
                        "description": "1110989572.04"
                      },
                      "communities": [
                        {
                          "type": "twitter",
                          "url": "http://www.twitter.com/bitcoin"
                        },
                        {
                          "type": "discord",
                          "url": "http://www.discord.com/bitcoin"
                        }
                      ],
                      "links": [
                        {
                          "type": "website",
                          "url": "http://www.bitcoin.com"
                        },
                        {
                          "type": "website",
                          "url": "http://www.bitcoin.com"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-currencies-id-metadata",
        "description": "Retrun the metadata for the currency ids provided",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "ids",
            "description": "list of currency ids to return the metadata for",
            "required": true
          }
        ]
      }
    },
    "/currencies/{id}/sparkline": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "id",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "operationId": "get-currencies-id-sparkline",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "enum": [
                "1m",
                "5m",
                "15m",
                "30m",
                "1h",
                "4h",
                "1d",
                "7d",
                "1m"
              ]
            },
            "in": "query",
            "name": "timeframe",
            "description": "timeframe to return the sparkline data for",
            "required": true
          },
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "id",
            "description": "currency id to return sparkline data for",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "start-time",
            "description": "Start time of the interval in RFC3339 (URI escaped)"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "end-time",
            "description": "End time of the interval in RFC3339 (URI escaped). If not provided, the current time is used.\n\n"
          }
        ],
        "requestBody": {},
        "description": "Get historic price of a currency for the specified timeframe and currency",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "object": {
                      "type": "object",
                      "properties": {
                        "timestamps": {
                          "type": "array",
                          "items": {}
                        }
                      }
                    },
                    "": {
                      "type": "object",
                      "properties": {
                        "pirces": {
                          "type": "array",
                          "items": {}
                        }
                      }
                    },
                    "currency": {
                      "type": "string"
                    },
                    "id": {
                      "type": "integer"
                    }
                  }
                },
                "examples": {
                  "example": {
                    "value": [
                      {
                        "currency": "BTC",
                        "id": "1",
                        "timestamps": [
                          "2018-04-03T16:00:00Z"
                        ],
                        "prices": [
                          "7436.82313"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/currencies/ticker": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "symbol": {
                      "type": "string"
                    },
                    "price": {
                      "type": "number"
                    },
                    "price_date": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "circulating_supply": {
                      "type": "string"
                    },
                    "max_supply": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "logo_url": {
                      "type": "string"
                    },
                    "market_cap": {
                      "type": "string"
                    },
                    "rank": {
                      "type": "string"
                    },
                    "ath": {
                      "type": "string"
                    },
                    "ath_timestamp": {
                      "type": "string"
                    },
                    "timeframe": {
                      "type": "object",
                      "properties": {
                        "price_change": {
                          "type": "string"
                        },
                        "price_change_pct": {
                          "type": "string"
                        },
                        "volume": {
                          "type": "string"
                        },
                        "volume_change_pct": {
                          "type": "string"
                        },
                        "marketcap_change": {
                          "type": "string"
                        },
                        "marketcap_change_pct": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "BTC",
                      "price": "8451.36516421",
                      "price_date": "2019-06-14",
                      "symbol": "BTC",
                      "circulating_supply": "17758462",
                      "max_supply": "21000000",
                      "name": "Bitcoin",
                      "logo_url": "https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/btc.svg",
                      "market_cap": "150083247116.70",
                      "rank": "1",
                      "high": "19404.81116899",
                      "high_timestamp": "2017-12-16",
                      "1d": {
                        "price_change": "269.75208019",
                        "price_change_pct": "0.03297053",
                        "volume": "1110989572.04",
                        "volume_change": "-24130098.49",
                        "volume_change_pct": "-0.02",
                        "market_cap_change": "4805518049.63",
                        "market_cap_change_pct": "0.03"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-currencies-ticker",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "ids",
            "required": true,
            "description": "Comma separated list of currencies IDs to filter result"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "convert",
            "description": "Currency to quote ticker price, market cap, and volume values. May be a Fiat Currency or Cryptocurrency. Default is USD"
          }
        ],
        "description": "Price and volume information for one or more currencies"
      }
    },
    "/market": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/market-metrics"
                },
                "examples": {
                  "example": {
                    "value": {
                      "btc_dominace": "",
                      "eth_dominance": "",
                      "fear-and-greed-index": {
                        "value": "987",
                        "value_classification": "A",
                        "timestamp": "2019-12-16T18:47:00.000Z"
                      },
                      "last_update": "2019-05-16T18:47:00.000Z",
                      "quote": {
                        "USD": {
                          "total_market_cap": 250385096532.124,
                          "total_volume_24h": 119270642406.968,
                          "total_volume_24h_reported": 1514905418.39087,
                          "altcoin_volume_24h": 119270642406.968,
                          "altcoin_volume_24h_reported": 1514905418.39087,
                          "altcoin_market_cap": 250385096532.124,
                          "last_updated": "2019-05-16T18:47:00.000Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-market-fcas",
        "description": "Returns the latest global cryptocurrency market metrics. Use the \"convert\" option to return market values in multiple fiat and cryptocurrency conversions in the same call."
      },
      "parameters": []
    },
    "/exchanges": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "": {
                      "$ref": "#/components/schemas/exchange"
                    }
                  }
                },
                "examples": {
                  "example": {
                    "value": [
                      {
                        "id": "2",
                        "name": "Binance",
                        "description": "Binance is a global cryptocurrency exchange that provides a platform for trading more than 100 cryptocurrencies. Since early 2018, Binance is considered as the biggest cryptocurrency exchange in the world in terms of trading volume",
                        "region": "eu",
                        "country": "Malta",
                        "volume_24h": "236797947.38",
                        "volume_7d": "4334436797947.38",
                        "volume_30d": "34343433797947.38",
                        "volume_24h_change_pct": "1.5563",
                        "volume_7d_change_pct": "2.3343",
                        "volume_30d_change_pct": "3.2333",
                        "blog": "http://binance.com/blog",
                        "twitter": "http://twitter.com/binance",
                        "telegram": "https://t.me/binanceexchange",
                        "fees": "https://www.binance.com/en/fee/schedule",
                        "website": "https://www.binance.com"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-exchanges",
        "description": "Get a list of supported exchnages"
      }
    },
    "/social/twitter": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {},
        "operationId": "get-social-twitter"
      }
    },
    "/news/categories": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/categories"
                }
              }
            }
          }
        },
        "operationId": "get-news-categories",
        "description": "Return a list of the available categories for news and social items."
      }
    }
  },
  "components": {
    "schemas": {
      "newsItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "example": 23
          },
          "source": {
            "type": "integer",
            "format": "int32",
            "example": 2
          },
          "projects": {
            "$ref": "#/components/schemas/project"
          },
          "categories": {
            "$ref": "#/components/schemas/categories"
          },
          "tags": {
            "$ref": "#/components/schemas/tags"
          },
          "link": {
            "type": "string",
            "format": "uri",
            "example": "https://www.newsbtc.com/2020/02/10/bitcoin-plunges-4-percent-bounces-back-10000-bull-trend-intact/"
          },
          "title": {
            "type": "string",
            "format": "byte"
          },
          "excerpt": {
            "type": "string",
            "format": "byte"
          },
          "full_article": {
            "type": "string",
            "format": "byte"
          },
          "publish_date": {
            "type": "string",
            "format": "date-time"
          },
          "sentiment": {
            "type": "string",
            "format": "byte"
          },
          "expert_level": {
            "type": "string",
            "format": "byte"
          }
        },
        "title": "",
        "x-examples": {
          "example-1": {}
        }
      },
      "tweets": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "example": 2
          },
          "source": {
            "$ref": "#/components/schemas/twitterSource"
          },
          "categories": {
            "$ref": "#/components/schemas/categories"
          },
          "projects": {
            "$ref": "#/components/schemas/project"
          },
          "tags": {
            "$ref": "#/components/schemas/tags"
          },
          "message": {
            "type": "string",
            "format": "byte"
          },
          "message_id": {
            "type": "integer",
            "format": "int64",
            "example": 1197150607519305700
          },
          "publish_date": {
            "type": "string",
            "format": "date-time"
          },
          "sentiment": {
            "type": "string",
            "format": "byte"
          },
          "retweet_count": {
            "type": "integer",
            "format": "int32",
            "example": 323
          },
          "favorite_count": {
            "type": "integer",
            "format": "int32",
            "example": 2332
          },
          "expert_level": {
            "type": "string",
            "format": "byte"
          }
        }
      },
      "twitterSource": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "example": 3
          },
          "username": {
            "type": "string",
            "format": "byte"
          },
          "region": {
            "type": "string",
            "format": "byte"
          },
          "bio": {
            "type": "string",
            "format": "byte"
          },
          "active": {
            "type": "boolean",
            "example": false
          }
        },
        "description": "Returns all twitter sources crypto investor stream uses"
      },
      "tags": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "example": 2
          },
          "name": {
            "type": "string",
            "format": "byte"
          }
        }
      },
      "categories": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "example": 2
          },
          "name": {
            "type": "string",
            "format": "byte"
          }
        }
      },
      "newsSource": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "example": 2
          },
          "name": {
            "type": "string",
            "format": "byte"
          },
          "url": {
            "type": "string",
            "format": "uri",
            "example": "www.newsbtc.com"
          }
        }
      },
      "project": {
        "required": [
          "id"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32",
            "example": 3
          },
          "name": {
            "type": "string",
            "format": "byte"
          },
          "image-url": {
            "type": "string",
            "format": "uri",
            "example": "https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/btc.svg"
          },
          "bio_short": {
            "type": "string",
            "format": "byte"
          },
          "bio_long": {
            "type": "string",
            "format": "byte"
          },
          "hq_location": {
            "type": "string",
            "format": "byte"
          },
          "platform": {
            "type": "integer",
            "format": "int32",
            "example": 23
          },
          "platform-token-address": {
            "type": "string",
            "format": "byte"
          }
        },
        "title": ""
      },
      "price": {
        "type": "object",
        "description": "",
        "properties": {
          "project_id": {
            "type": "integer"
          },
          "symbol": {
            "type": "string"
          },
          "open_day": {
            "type": "number"
          },
          "high_day": {
            "type": "number"
          },
          "low_day": {
            "type": "number"
          },
          "open_24h": {
            "type": "number"
          },
          "high_24": {
            "type": "number"
          },
          "low_24h": {
            "type": "number"
          },
          "open_hour": {
            "type": "number"
          },
          "high_hour": {
            "type": "number"
          },
          "low_hour": {
            "type": "number"
          },
          "price": {
            "type": "string"
          },
          "price_change_pct_30d": {
            "type": "number"
          },
          "price_change_pct_7d": {
            "type": "number"
          },
          "price_change_pct_1d": {
            "type": "number"
          },
          "price_change_pct_4h": {
            "type": "number"
          },
          "price_change_pct_1h": {
            "type": "number"
          },
          "price_change_pct_30m": {
            "type": "number"
          },
          "price_change_pct_15m": {
            "type": "number"
          },
          "price_change_pct_10m": {
            "type": "number"
          },
          "price_change_pct_5m": {
            "type": "number"
          },
          "price_change_pct_4m": {
            "type": "number"
          },
          "price_change_pct_3m": {
            "type": "number"
          },
          "price_change_pct_2m": {
            "type": "number"
          },
          "price_change_pct_1m": {
            "type": "number"
          }
        }
      },
      "fearAndGreed": {
        "type": "object",
        "properties": {
          "value": {
            "type": "integer",
            "format": "int32",
            "example": 23
          },
          "value_classification": {
            "type": "string",
            "format": "byte"
          },
          "timestamp": {
            "type": "string",
            "format": "date-time"
          }
        },
        "x-examples": {
          "example-1": {
            "value": "987",
            "value_classification": "A",
            "timestamp": "2019-12-16T18:47:00.000Z"
          }
        }
      },
      "priceSparkline": {
        "title": "priceSparkline",
        "type": "object",
        "properties": {
          "price_usd": {
            "type": "number"
          },
          "itimestamp": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "exchange": {
        "title": "exchange",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "region": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "volume_24h": {
            "type": "number"
          },
          "volumen_7d": {
            "type": "number"
          },
          "volume_30d": {
            "type": "number"
          },
          "volume_24_change_percent": {
            "type": "number"
          },
          "volume_7d_change_percent": {
            "type": "number"
          },
          "volume_30d_change_percent": {
            "type": "number"
          },
          "active": {
            "type": "boolean"
          },
          "last_update": {
            "type": "string",
            "format": "date-time"
          },
          "blog": {
            "type": "string",
            "format": "uri"
          },
          "twitter": {
            "type": "string",
            "format": "uri"
          },
          "telegram": {
            "type": "string",
            "format": "uri"
          },
          "fees": {
            "type": "string",
            "format": "uri"
          },
          "website": {
            "type": "string",
            "format": "uri"
          }
        },
        "x-examples": {
          "example": [
            {
              "id": "2",
              "name": "Binance",
              "description": "Binance is a global cryptocurrency exchange that provides a platform for trading more than 100 cryptocurrencies. Since early 2018, Binance is considered as the biggest cryptocurrency exchange in the world in terms of trading volume",
              "region": "eu",
              "country": "Malta",
              "volume_24h": "236797947.38",
              "volume_7d": "4334436797947.38",
              "volume_30d": "34343433797947.38",
              "volume_24h_change_pct": "1.5563",
              "volume_7d_change_pct": "2.3343",
              "volume_30d_change_pct": "3.2333",
              "blog": "http://binance.com/blog",
              "twitter": "http://twitter.com/binance",
              "telegram": "https://t.me/binanceexchange",
              "fees": "https://www.binance.com/en/fee/schedule",
              "website": "https://www.binance.com"
            }
          ]
        }
      },
      "fcas": {
        "title": "fcas",
        "type": "object",
        "properties": {
          "project_id": {
            "type": "integer"
          },
          "timestamp": {
            "type": "string",
            "format": "date-time"
          },
          "score": {
            "type": "integer"
          },
          "grade": {
            "type": "integer"
          }
        },
        "description": "FCAS ratings for all available currencies"
      },
      "currencies": {
        "title": "currencies",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "symbol": {
            "type": "string"
          },
          "circulating_supply": {
            "type": "string"
          },
          "total_supply": {
            "type": "string"
          },
          "max_supply": {
            "type": "string"
          },
          "ath_usd": {
            "type": "string"
          },
          "marketcap_usd": {
            "type": "string"
          },
          "project": {
            "$ref": "#/components/schemas/project"
          }
        }
      },
      "market-metrics": {
        "title": "market-metrics",
        "type": "object",
        "description": "",
        "x-examples": {
          "example": {
            "btc_dominace": "",
            "eth_dominance": "",
            "fear-and-greed-index": {
              "value": "987",
              "value_classification": "A",
              "timestamp": "2019-12-16T18:47:00.000Z"
            },
            "last_update": "2019-05-16T18:47:00.000Z",
            "quote": {
              "USD": {
                "total_market_cap": 250385096532.124,
                "total_volume_24h": 119270642406.968,
                "total_volume_24h_reported": 1514905418.39087,
                "altcoin_volume_24h": 119270642406.968,
                "altcoin_volume_24h_reported": 1514905418.39087,
                "altcoin_market_cap": 250385096532.124,
                "last_updated": "2019-05-16T18:47:00.000Z"
              }
            }
          }
        },
        "properties": {
          "quote": {
            "type": "object",
            "description": "",
            "properties": {
              "quote_currency": {
                "type": "object",
                "properties": {
                  "total_marketcap": {
                    "type": "number"
                  },
                  "total_volume_24h": {
                    "type": "number"
                  },
                  "altcoin_volume_24h": {
                    "type": "number"
                  },
                  "altcoin_marketcap": {
                    "type": "number"
                  },
                  "last_update": {
                    "type": "string",
                    "format": "date-time"
                  }
                }
              }
            }
          },
          "eth-dominance": {
            "type": "string"
          },
          "btc-dominance": {
            "type": "string"
          },
          "fear-and-greed": {
            "$ref": "#/components/schemas/fearAndGreed"
          }
        }
      },
      "market-volume": {
        "title": "volume",
        "type": "object",
        "properties": {
          "total_market_cap": {
            "type": "string"
          },
          "total_volume_24h": {
            "type": "string"
          },
          "total_volume_24h_reported": {
            "type": "string"
          },
          "altcoin_volume_24h": {
            "type": "string"
          },
          "altcoin_volume_24h_reported": {
            "type": "string"
          }
        },
        "description": "Market volume metrics represented in USD",
        "x-examples": {}
      },
      "currency-metadata": {
        "title": "currency-metadata",
        "type": "object",
        "description": "Returns the metadata for a list of specific currency",
        "properties": {
          "currency_id": {
            "type": "string"
          },
          "logo_url": {
            "type": "string"
          },
          "bio_short": {
            "type": "string"
          },
          "bio_long": {
            "type": "string"
          },
          "bio_keywords": {
            "type": "string"
          },
          "hq_location": {
            "type": "string"
          },
          "vertical_types": {
            "$ref": "#/components/schemas/vertical-types"
          },
          "links": {
            "$ref": "#/components/schemas/links"
          },
          "communities": {
            "$ref": "#/components/schemas/communities"
          }
        },
        "x-examples": {
          "example": {
            "id": "1",
            "symbol": "BTC",
            "logo_url": "https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/btc.svg",
            "bio_short": "Bitcoin is a cryptocurrency.",
            "bio_long": "Bitcoin is a cryptocurrency. It is a decentralized digital currency",
            "bio_keywords": "BTC,Bitcoin",
            "hq_location": "Malta",
            "vertical_types": {
              "id": "269.75208019",
              "name": "0.03297053",
              "description": "1110989572.04"
            },
            "communities": [
              {
                "type": "twitter",
                "url": "http://www.twitter.com/bitcoin"
              },
              {
                "type": "discord",
                "url": "http://www.discord.com/bitcoin"
              }
            ],
            "links": [
              {
                "type": "website",
                "url": "http://www.bitcoin.com"
              },
              {
                "type": "website",
                "url": "http://www.bitcoin.com"
              }
            ]
          }
        }
      },
      "links": {
        "title": "links",
        "type": "object",
        "description": "Returns links related to the currency",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "website",
              "email",
              "explorer",
              "whitepaper",
              "wallet",
              "github",
              "announcement",
              "bounty-program"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "communities": {
        "title": "communities",
        "type": "object",
        "description": "Return the communities related to the currency",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "discord",
              "telegram",
              "facebook",
              "forum",
              "medium",
              "slack",
              "twitter",
              "reddit",
              "bitcoin-talk",
              "instagram"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "vertical-types": {
        "title": "vertical-types",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {}
  }
}